server:
  port: 80
spring:
  main:
    web-application-type: reactive
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product_command_route
          uri: http://localhost:81
          predicates:
            - Path=/product-command/**
          #filters:
            #- RewritePath=/product-command/(?<path>.*), /$\{path}
        - id: product_query_route
          uri: http://localhost:82
          predicates:
            - Path=/product-query/**
            #filters:
            #- RewritePath=/product-query/(?<path>.*), /$\{path}

springdoc:
  packages-to-scan: com.zamani.springcloudgateway
  paths-to-match: /**/api/**
  swagger-ui:
    path: /api-docs

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG




