server:
  port: 82
spring:
  application:
    name: product-query
  jackson.serialization.indent_output: true

redis:
  host: localhost
  port: 6379
active-mq:
  broker-url: tcp://localhost:61616
  topic: product-events-topic
springdoc:
  packages-to-scan: com.zamani
  paths-to-match: /**/api/**
  version: 1.5.8
  swagger-ui:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
      diskspace:
        enabled: false
      circuitbreakers:
        enabled: true
      ratelimiters:
        enabled: false
